from flask import Flask, make_response, redirect, url_for
from flask.templating import render_template
import datetime

app = Flask('__main__')



@app.route('/yourhome', methods=['GET', 'POST'])
def home():
    now = datetime.datetime.now()
    return render_template('home.html', curr_now=now)

@app.route('/about')
def about():
    headers = {"Content-Type": "application/json"}
    return make_response("This response is generated by Make Response function", 201, headers)


# @app.route('/base')
@app.route('/search')
# def base():
def search():
    #return redirect('/yourhome')
    # return redirect(url_for('home'))
    return redirect('http://www.google.com')



# ---------------------------------- HTTP METHODS BELOW------------------------------

@app.route('/base')
def base():
    return render_template('base.html')



if __name__ == '__main__':
    app.run(debug=True)